# **Limpieza de datos nulos  (Facturación, devoluciones, crédito, clientes)**
### **Equipo 3 | Alumnos:**
**José María Colombres Elguea | A01734153**

**Santiago Gael Gallardo Parente | A01734347**

**Miguel Sebastián Carreto Bahena | A01735592**

In [ ]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Leer archivo**

In [ ]:
df_facturacion = pd.read_excel("Facturacion_D_NC_C.xlsx",sheet_name="FACTURACION")
df_facturacion

,CVE_DOC,CLIENTE,STATUS,VENDEDOR,FECHA_ELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,TOTAL,RFC
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.000,0.0,3980.000,YOR-030722-UV8
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.000,0.0,1550.000,PPE 490224 HI0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.000,0.0,1550.000,PPE 490224 HI0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.000,0.0,1550.000,PPE 490224 HI0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.440,0.0,2435.440,MPI130528640
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10956,F40372,4802,E,2.0,2023-03-15 12:53:44.607,2023-03-15,2023-03-15 00:00:00,2023-03-15,NaT,2178.000,0.0,2178.000,SEAR640814NW7
10957,F40373,8545,E,2.0,2023-03-15 13:39:40.950,2023-03-15,2023-03-15 00:00:00,2023-03-15,NaT,607.250,0.0,607.250,JAG2108104Q9
10958,F40374,O,E,2.0,2023-03-16 09:54:32.857,2023-03-16,2023-03-16 00:00:00,2023-03-16,NaT,567.757,0.0,567.757,PPQ000825TXA
10959,F40375,3916,E,1.0,2023-03-16 10:04:51.323,2023-03-16,2023-03-06 00:00:00,2023-03-31,NaT,1944.950,0.0,1944.950,VIN800602NL9
10960,F40376,4797,E,2.0,2023-03-16 13:26:13.840,2023-03-16,2023-03-15 00:00:00,2023-03-31,NaT,6813.000,0.0,6813.000,RED090217R15

In [ ]:
df_devoluciones = pd.read_excel("Facturacion_D_NC_C.xlsx",sheet_name="DEVOLUCIONES")
df_devoluciones

,TIP_OP,CVE_DEV,CLIENTE,STATUS,VENDEDOR,CVE_PEDI,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_FIN,FECHA_ELAB,RFC,SERIE,FOLIO,CVE_DOC
0,D,D00501,1703,E,1.0,PV00039,2019-09-30,2019-09-06,2019-09-30,NaT,50994.00,0,2019-09-30 18:29:49.000,INE 911127 JG1,D,501,F29599
1,D,DEV0000000001,1852,E,2.0,F29896,2019-10-09,2019-09-17,2019-10-09,NaT,7125.90,0,2019-10-09 14:58:36.000,IPM-620322-6B4,DEV,1,F29596
2,D,DEV00002,5149,E,2.0,F29604,2019-10-10,2019-09-23,2019-10-10,NaT,2726.52,0,2019-10-10 13:41:27.000,LGV-000406-U16,DEV,2,F29604
3,D,DEV00003,3222,E,2.0,F29605,2019-10-10,2019-09-23,2019-10-10,NaT,1363.26,0,2019-10-10 13:49:44.000,LGQ-020801-KQ3,DEV,3,F29605
4,D,DEV00004,664,E,2.0,F29616,2019-10-10,2019-09-18,2019-10-10,NaT,4232.25,0,2019-10-10 14:12:13.000,CID-910926-P7A,DEV,4,F29616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,D,DEV00189,2768,E,1.0,PP03914,2023-02-22,2022-12-21,2023-02-22,NaT,4880.00,0,2023-02-22 17:30:38.537,CPA040625NA1,DEV,189,F39812
190,D,DEV00190,2768,E,1.0,PV01216,2023-02-22,2023-02-08,2023-02-22,NaT,17768.00,0,2023-02-22 17:34:52.157,CPA040625NA1,DEV,190,F40172
191,D,DEV00191,2768,E,1.0,PP04020,2023-02-22,2023-02-08,2023-02-22,NaT,8816.00,0,2023-02-22 17:35:53.687,CPA040625NA1,DEV,191,F40121
192,D,DEV00192,2768,E,1.0,PP04019,2023-02-22,2023-02-08,2023-02-22,NaT,4070.00,0,2023-02-22 17:36:48.257,CPA040625NA1,DEV,192,F40120
193,D,DEV00193,2768,E,1.0,PP04018,2023-02-22,2023-02-08,2023-02-22,NaT,1660.00,0,2023-02-22 17:39:28.923,CPA040625NA1,DEV,193,F40119

In [ ]:
df_notascredito = pd.read_excel("Facturacion_D_NC_C.xlsx",sheet_name="NOTAS DE CREDITO")
df_notascredito

,TIP_OP,CVE_NC,CLIENTE,STATUS,VENDEDOR,CVE_PEDI,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,FECHA_ELAB,RFC,SERIE,FOLIO
0,E,NC00247,6826,C,2.0,NaN,2019-09-10,2019-09-10,2019-09-10,2019-09-13,603.4480,2019-09-10 11:49:34.000,DEQJ760331UC0,NC,247
1,E,NC00248,5437,E,2.0,NaN,2019-09-11,2019-09-11,2019-09-11,NaT,431.0344,2019-09-11 08:54:14.000,OIM 060801 GH5,NC,248
2,E,NC00249,1240,C,2.0,NaN,2019-09-11,2019-09-11,2019-09-11,2019-09-18,4135.0000,2019-09-11 18:23:06.000,REMA-710901-G64,NC,249
3,E,NC00250,4889,E,3.0,NaN,2019-09-12,2019-09-12,2019-09-12,NaT,258.6200,2019-09-12 14:54:54.000,MAPA 710520 A10,NC,250
4,E,NC00251,6834,E,2.0,F29452,2019-09-19,2019-09-10,2019-09-19,NaT,919.4560,2019-09-19 10:59:28.000,NPR111214391,NC,251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,E,NC00757,8224,E,2.0,PP03949,2023-01-31,2023-01-11,2023-01-31,NaT,862.0689,2023-01-31 13:33:08.167,CASM6606098V1,NC,757
511,E,NC00758,6839,E,2.0,PP03927,2023-01-31,2023-01-04,2023-01-31,NaT,2595.4137,2023-01-31 16:22:19.703,ALK180903DT6,NC,758
512,E,NC00759,5923,E,2.0,PP03948,2023-02-07,2023-01-25,2023-02-07,NaT,350.0000,2023-02-07 11:36:18.953,DME111122F34,NC,759
513,E,NC00760,5926,E,2.0,PP03959 REVISION,2023-02-07,2023-01-31,2023-02-07,NaT,350.0000,2023-02-07 17:32:21.910,XAXX010101000,NC,760
514,E,NC00761,8842,E,2.0,PP04087,2023-03-06,2023-03-01,2023-03-06,NaT,3272.0000,2023-03-06 16:12:08.750,MAMN580503DK3,NC,761

In [ ]:
df_clientes = pd.read_excel("Facturacion_D_NC_C.xlsx",sheet_name="CLIENTES",index_col='CLIENTE')
df_clientes

                      RFC                                           NOMBRE
CLIENTE
         1   AMQ911121AL8  ASOCIACION DE MIPYMES INDUSTRIALES DE QUERETARO
         2   GCA900118AX6                           GRUPO COMERCIAL ACOMEE
         3  AAVJ630625FJ4                  ANDRADE VILLANUEVA JUAN GERARDO
         5   MDI8312134L0                            MANUFACTURAS DIVERSAS
         6   MME640509AS8                           MANUFACTURAS METALICAS
...                   ...                                              ...
MOSTR                 NaN                                              NaN
N.I.        XAXX010101000                       DEPOSITOS NO IDENTIFICADOS
O            PPQ000825TXA            POLIETILENOS Y PRODUCTOS DE QUERETARO
P            MIR060120RS1      MANTEMINIENTO INDUSTRIAL Y RESIDENCIAL ESVE
PB           RPA040310JS2                           REHRIG PACIFIC COMPANY

[5025 rows x 2 columns]

# **Limpieza por hoja**

## **Facturación**

En la sesión con el socio formador, Francisco indicó que las columnas de valor para el análisis en la hoja de facturación son: FECHA_ELAB y FECHA_VEN. Por lo que se decidió eliminar las columnas de FECHA_DOC y FECHA_ENT.

In [ ]:
df_facturacion = df_facturacion.drop("FECHA_DOC",axis=1)
df_facturacion = df_facturacion.drop("FECHA_ENT",axis=1)
df_facturacion

,CVE_DOC,CLIENTE,STATUS,VENDEDOR,FECHA_ELAB,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,TOTAL,RFC
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-18,2019-09-04,3980.000,0.0,3980.000,YOR-030722-UV8
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-10-03,2019-09-03,1550.000,0.0,1550.000,PPE 490224 HI0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-10-03,2019-09-03,1550.000,0.0,1550.000,PPE 490224 HI0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-10-03,2019-09-17,1550.000,0.0,1550.000,PPE 490224 HI0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-10,2435.440,0.0,2435.440,MPI130528640
...,...,...,...,...,...,...,...,...,...,...,...
10956,F40372,4802,E,2.0,2023-03-15 12:53:44.607,2023-03-15,NaT,2178.000,0.0,2178.000,SEAR640814NW7
10957,F40373,8545,E,2.0,2023-03-15 13:39:40.950,2023-03-15,NaT,607.250,0.0,607.250,JAG2108104Q9
10958,F40374,O,E,2.0,2023-03-16 09:54:32.857,2023-03-16,NaT,567.757,0.0,567.757,PPQ000825TXA
10959,F40375,3916,E,1.0,2023-03-16 10:04:51.323,2023-03-31,NaT,1944.950,0.0,1944.950,VIN800602NL9
10960,F40376,4797,E,2.0,2023-03-16 13:26:13.840,2023-03-31,NaT,6813.000,0.0,6813.000,RED090217R15

Con la función info se puede observar que la columna de Vendedor tiene algunos registros nulos, por lo que en vez de eliminarlos se asignará el valor 0 a las columnas nulas. Para la columna fecha cancela se creo un data frame filtrado solo con las que tienen valores no nulos y se borra del df original

In [ ]:
df_facturacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10961 entries, 0 to 10960
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CVE_DOC        10961 non-null  object
 1   CLIENTE        10961 non-null  object
 2   STATUS         10961 non-null  object
 3   VENDEDOR       10913 non-null  float64
 4   FECHA_ELAB     10961 non-null  datetime64[ns]
 5   FECHA_VEN      10961 non-null  datetime64[ns]
 6   FECHA_CANCELA  358 non-null    datetime64[ns]
 7   CAN_TOT        10961 non-null  float64
 8   DES_TOT        10961 non-null  float64
 9   TOTAL          10961 non-null  float64
 10  RFC            10961 non-null  object
dtypes: datetime64[ns](3), float64(4), object(4)
memory usage: 942.1+ KB

In [ ]:
df_facturacion['VENDEDOR'] = df_facturacion['VENDEDOR'].fillna(0)
df_facturacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10961 entries, 0 to 10960
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CVE_DOC        10961 non-null  object
 1   CLIENTE        10961 non-null  object
 2   STATUS         10961 non-null  object
 3   VENDEDOR       10961 non-null  float64
 4   FECHA_ELAB     10961 non-null  datetime64[ns]
 5   FECHA_VEN      10961 non-null  datetime64[ns]
 6   FECHA_CANCELA  358 non-null    datetime64[ns]
 7   CAN_TOT        10961 non-null  float64
 8   DES_TOT        10961 non-null  float64
 9   TOTAL          10961 non-null  float64
 10  RFC            10961 non-null  object
dtypes: datetime64[ns](3), float64(4), object(4)
memory usage: 942.1+ KB

In [ ]:
df_facturacionfiltro = df_facturacion[df_facturacion['FECHA_CANCELA'].notnull()]

In [ ]:
df_facturacionfiltro

,CVE_DOC,CLIENTE,STATUS,VENDEDOR,FECHA_ELAB,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,TOTAL,RFC
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-18,2019-09-04,3980.000,0.0,3980.000,YOR-030722-UV8
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-10-03,2019-09-03,1550.000,0.0,1550.000,PPE 490224 HI0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-10-03,2019-09-03,1550.000,0.0,1550.000,PPE 490224 HI0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-10-03,2019-09-17,1550.000,0.0,1550.000,PPE 490224 HI0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-10,2435.440,0.0,2435.440,MPI130528640
...,...,...,...,...,...,...,...,...,...,...,...
10671,F40087,2483,C,2.0,2023-02-07 11:40:15.027,2023-02-07,2023-02-07,550.000,0.0,550.000,AMA0905135K5
10677,F40093,5936,C,2.0,2023-02-07 14:19:08.020,2023-03-09,2023-02-09,903.073,0.0,903.073,BQU151118FA2
10680,F40096,8708,C,6.0,2023-02-07 16:41:23.167,2023-02-28,2023-02-08,19790.000,0.0,19790.000,TAU2105114C2
10720,F40136,6381,C,2.0,2023-02-14 13:17:22.143,2023-02-14,2023-02-14,4172.000,0.0,4172.000,HUOA650427NZ0
10823,F40239,5416,C,2.0,2023-02-24 16:32:26.607,2023-02-24,2023-02-24,3815.440,0.0,3815.440,SARH5910272R0

In [ ]:
df_facturacion = df_facturacion.drop("FECHA_CANCELA",axis=1)
df_facturacion

,CVE_DOC,CLIENTE,STATUS,VENDEDOR,FECHA_ELAB,FECHA_VEN,CAN_TOT,DES_TOT,TOTAL,RFC
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-18,3980.000,0.0,3980.000,YOR-030722-UV8
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-10-03,1550.000,0.0,1550.000,PPE 490224 HI0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-10-03,1550.000,0.0,1550.000,PPE 490224 HI0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-10-03,1550.000,0.0,1550.000,PPE 490224 HI0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2435.440,0.0,2435.440,MPI130528640
...,...,...,...,...,...,...,...,...,...,...
10956,F40372,4802,E,2.0,2023-03-15 12:53:44.607,2023-03-15,2178.000,0.0,2178.000,SEAR640814NW7
10957,F40373,8545,E,2.0,2023-03-15 13:39:40.950,2023-03-15,607.250,0.0,607.250,JAG2108104Q9
10958,F40374,O,E,2.0,2023-03-16 09:54:32.857,2023-03-16,567.757,0.0,567.757,PPQ000825TXA
10959,F40375,3916,E,1.0,2023-03-16 10:04:51.323,2023-03-31,1944.950,0.0,1944.950,VIN800602NL9
10960,F40376,4797,E,2.0,2023-03-16 13:26:13.840,2023-03-31,6813.000,0.0,6813.000,RED090217R15

## **Devoluciones**

Se decidió eliminar las columnas de FECHA_DOC y FECHA_ENT, además de la columna de SERIE que tenía un mismo valor. También se eliminó la columna DES_FIN que tenía todos los valores en 0

In [ ]:
df_devoluciones=df_devoluciones.drop(["FECHA_DOC","FECHA_ENT","SERIE","DES_FIN"],axis=1)
df_devoluciones

,TIP_OP,CVE_DEV,CLIENTE,STATUS,VENDEDOR,CVE_PEDI,FECHA_VEN,FECHA_CANCELA,CAN_TOT,FECHA_ELAB,RFC,FOLIO,CVE_DOC
0,D,D00501,1703,E,1.0,PV00039,2019-09-30,NaT,50994.00,2019-09-30 18:29:49.000,INE 911127 JG1,501,F29599
1,D,DEV0000000001,1852,E,2.0,F29896,2019-10-09,NaT,7125.90,2019-10-09 14:58:36.000,IPM-620322-6B4,1,F29596
2,D,DEV00002,5149,E,2.0,F29604,2019-10-10,NaT,2726.52,2019-10-10 13:41:27.000,LGV-000406-U16,2,F29604
3,D,DEV00003,3222,E,2.0,F29605,2019-10-10,NaT,1363.26,2019-10-10 13:49:44.000,LGQ-020801-KQ3,3,F29605
4,D,DEV00004,664,E,2.0,F29616,2019-10-10,NaT,4232.25,2019-10-10 14:12:13.000,CID-910926-P7A,4,F29616
...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,D,DEV00189,2768,E,1.0,PP03914,2023-02-22,NaT,4880.00,2023-02-22 17:30:38.537,CPA040625NA1,189,F39812
190,D,DEV00190,2768,E,1.0,PV01216,2023-02-22,NaT,17768.00,2023-02-22 17:34:52.157,CPA040625NA1,190,F40172
191,D,DEV00191,2768,E,1.0,PP04020,2023-02-22,NaT,8816.00,2023-02-22 17:35:53.687,CPA040625NA1,191,F40121
192,D,DEV00192,2768,E,1.0,PP04019,2023-02-22,NaT,4070.00,2023-02-22 17:36:48.257,CPA040625NA1,192,F40120
193,D,DEV00193,2768,E,1.0,PP04018,2023-02-22,NaT,1660.00,2023-02-22 17:39:28.923,CPA040625NA1,193,F40119

In [ ]:
df_devoluciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TIP_OP         194 non-null    object
 1   CVE_DEV        194 non-null    object
 2   CLIENTE        194 non-null    object
 3   STATUS         194 non-null    object
 4   VENDEDOR       191 non-null    float64
 5   CVE_PEDI       188 non-null    object
 6   FECHA_VEN      194 non-null    datetime64[ns]
 7   FECHA_CANCELA  7 non-null      datetime64[ns]
 8   CAN_TOT        194 non-null    float64
 9   FECHA_ELAB     194 non-null    datetime64[ns]
 10  RFC            194 non-null    object
 11  FOLIO          194 non-null    int64
 12  CVE_DOC        183 non-null    object
dtypes: datetime64[ns](3), float64(2), int64(1), object(7)
memory usage: 19.8+ KB

Se asigna a los valores nulos de la columna vendedor el 0 como identificador de aquellas devoluciones de las cuales no se tiene registro de vendedor

In [ ]:
df_devoluciones['VENDEDOR'] = df_devoluciones['VENDEDOR'].fillna(0)

Se eliminarán aquellos registros nulos de la columna CVE_PEDI. La condicion es que si esta vacia la fila, busque en la columna de CVE_DOC el formato F12345 (Ejemplo).

In [ ]:
#PASAMOS LOS VALORES DE CVE_DOC A CVE_PEDI SI LA CELDA ES NULA
nulos = df_devoluciones['CVE_PEDI'].isnull()
patron = 'F\d{5}'

coincidencias = df_devoluciones.loc[nulos, 'CVE_DOC'].str.contains(patron)

df_devoluciones.loc[nulos & coincidencias, 'CVE_PEDI'] = df_devoluciones.loc[nulos & coincidencias, 'CVE_DOC']
df_devoluciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TIP_OP         194 non-null    object
 1   CVE_DEV        194 non-null    object
 2   CLIENTE        194 non-null    object
 3   STATUS         194 non-null    object
 4   VENDEDOR       194 non-null    float64
 5   CVE_PEDI       194 non-null    object
 6   FECHA_VEN      194 non-null    datetime64[ns]
 7   FECHA_CANCELA  7 non-null      datetime64[ns]
 8   CAN_TOT        194 non-null    float64
 9   FECHA_ELAB     194 non-null    datetime64[ns]
 10  RFC            194 non-null    object
 11  FOLIO          194 non-null    int64
 12  CVE_DOC        183 non-null    object
dtypes: datetime64[ns](3), float64(2), int64(1), object(7)
memory usage: 19.8+ KB

In [ ]:
#PASAMOS LOS VALORES DE CVE_PEDI A CVE_DOC SI LA CELDA ES NULA
nulos2 = df_devoluciones['CVE_DOC'].isnull()
patron2 = 'F\d{5}'

coincidencias2 = df_devoluciones.loc[nulos2, 'CVE_PEDI'].str.contains(patron2)

df_devoluciones.loc[nulos2 & coincidencias2, 'CVE_DOC'] = df_devoluciones.loc[nulos2 & coincidencias2, 'CVE_PEDI']
df_devoluciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TIP_OP         194 non-null    object
 1   CVE_DEV        194 non-null    object
 2   CLIENTE        194 non-null    object
 3   STATUS         194 non-null    object
 4   VENDEDOR       194 non-null    float64
 5   CVE_PEDI       194 non-null    object
 6   FECHA_VEN      194 non-null    datetime64[ns]
 7   FECHA_CANCELA  7 non-null      datetime64[ns]
 8   CAN_TOT        194 non-null    float64
 9   FECHA_ELAB     194 non-null    datetime64[ns]
 10  RFC            194 non-null    object
 11  FOLIO          194 non-null    int64
 12  CVE_DOC        185 non-null    object
dtypes: datetime64[ns](3), float64(2), int64(1), object(7)
memory usage: 19.8+ KB

In [ ]:
df_devoluciones['CVE_DOC'] = df_devoluciones['CVE_DOC'].fillna('SI0000')
df_devoluciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TIP_OP         194 non-null    object
 1   CVE_DEV        194 non-null    object
 2   CLIENTE        194 non-null    object
 3   STATUS         194 non-null    object
 4   VENDEDOR       194 non-null    float64
 5   CVE_PEDI       194 non-null    object
 6   FECHA_VEN      194 non-null    datetime64[ns]
 7   FECHA_CANCELA  7 non-null      datetime64[ns]
 8   CAN_TOT        194 non-null    float64
 9   FECHA_ELAB     194 non-null    datetime64[ns]
 10  RFC            194 non-null    object
 11  FOLIO          194 non-null    int64
 12  CVE_DOC        194 non-null    object
dtypes: datetime64[ns](3), float64(2), int64(1), object(7)
memory usage: 19.8+ KB

In [ ]:
df_devolucionesfiltro = df_devoluciones[df_devoluciones['FECHA_CANCELA'].notnull()]

In [ ]:
df_devoluciones = df_devoluciones.drop("FECHA_CANCELA",axis=1)
df_devoluciones

,TIP_OP,CVE_DEV,CLIENTE,STATUS,VENDEDOR,CVE_PEDI,FECHA_VEN,CAN_TOT,FECHA_ELAB,RFC,FOLIO,CVE_DOC
0,D,D00501,1703,E,1.0,PV00039,2019-09-30,50994.00,2019-09-30 18:29:49.000,INE 911127 JG1,501,F29599
1,D,DEV0000000001,1852,E,2.0,F29896,2019-10-09,7125.90,2019-10-09 14:58:36.000,IPM-620322-6B4,1,F29596
2,D,DEV00002,5149,E,2.0,F29604,2019-10-10,2726.52,2019-10-10 13:41:27.000,LGV-000406-U16,2,F29604
3,D,DEV00003,3222,E,2.0,F29605,2019-10-10,1363.26,2019-10-10 13:49:44.000,LGQ-020801-KQ3,3,F29605
4,D,DEV00004,664,E,2.0,F29616,2019-10-10,4232.25,2019-10-10 14:12:13.000,CID-910926-P7A,4,F29616
...,...,...,...,...,...,...,...,...,...,...,...,...
189,D,DEV00189,2768,E,1.0,PP03914,2023-02-22,4880.00,2023-02-22 17:30:38.537,CPA040625NA1,189,F39812
190,D,DEV00190,2768,E,1.0,PV01216,2023-02-22,17768.00,2023-02-22 17:34:52.157,CPA040625NA1,190,F40172
191,D,DEV00191,2768,E,1.0,PP04020,2023-02-22,8816.00,2023-02-22 17:35:53.687,CPA040625NA1,191,F40121
192,D,DEV00192,2768,E,1.0,PP04019,2023-02-22,4070.00,2023-02-22 17:36:48.257,CPA040625NA1,192,F40120
193,D,DEV00193,2768,E,1.0,PP04018,2023-02-22,1660.00,2023-02-22 17:39:28.923,CPA040625NA1,193,F40119

In [30]:
df_devoluciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   TIP_OP      194 non-null    object
 1   CVE_DEV     194 non-null    object
 2   CLIENTE     194 non-null    object
 3   STATUS      194 non-null    object
 4   VENDEDOR    194 non-null    float64
 5   CVE_PEDI    194 non-null    object
 6   FECHA_VEN   194 non-null    datetime64[ns]
 7   CAN_TOT     194 non-null    float64
 8   FECHA_ELAB  194 non-null    datetime64[ns]
 9   RFC         194 non-null    object
 10  FOLIO       194 non-null    int64
 11  CVE_DOC     194 non-null    object
dtypes: datetime64[ns](2), float64(2), int64(1), object(7)
memory usage: 18.3+ KB

## **Notas de credito**

In [ ]:
#Checar si hay valores nulos por columna
valores_nulos=df_notascredito.isnull().sum()
valores_nulos

TIP_OP             0
CVE_NC             0
CLIENTE            0
STATUS             0
VENDEDOR          10
CVE_PEDI          11
FECHA_DOC          0
FECHA_ENT          0
FECHA_VEN          0
FECHA_CANCELA    497
CAN_TOT            0
FECHA_ELAB         0
RFC                0
SERIE              0
FOLIO              0
dtype: int64

In [ ]:
#Filtro de fechas canceladas 
filtro_cancelaciones = df_notascredito[df_notascredito['FECHA_CANCELA'].notnull()]
filtro_cancelaciones.head()

,TIP_OP,CVE_NC,CLIENTE,STATUS,VENDEDOR,CVE_PEDI,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,FECHA_ELAB,RFC,SERIE,FOLIO
0,E,NC00247,6826,C,2.0,NaN,2019-09-10,2019-09-10,2019-09-10,2019-09-13,603.448,2019-09-10 11:49:34,DEQJ760331UC0,NC,247
2,E,NC00249,1240,C,2.0,NaN,2019-09-11,2019-09-11,2019-09-11,2019-09-18,4135.000,2019-09-11 18:23:06,REMA-710901-G64,NC,249
36,E,NC00283,3886,C,3.0,F30023,2019-10-29,2019-10-29,2019-10-29,2020-06-24,4968.600,2019-10-29 09:29:01,GOMT-670106-NY2,NC,283
82,E,NC00329,209,C,2.0,F30976,2020-02-07,2020-01-31,2020-02-07,2020-02-07,6391.380,2020-02-07 10:27:44,IEA-930426-5N2,NC,329
136,E,NC00383,6059,C,3.0,F30476,2020-04-30,2019-12-02,2020-04-30,2020-05-01,10048.050,2020-04-30 12:58:33,THU130315QA3,NC,383

In [ ]:
#eliminar columna FECHA_CANCELA del data frame original
df_notascredito = df_notascredito.drop(columns=['FECHA_CANCELA'])
df_notascredito.head()

,TIP_OP,CVE_NC,CLIENTE,STATUS,VENDEDOR,CVE_PEDI,FECHA_DOC,FECHA_ENT,FECHA_VEN,CAN_TOT,FECHA_ELAB,RFC,SERIE,FOLIO
0,E,NC00247,6826,C,2.0,NaN,2019-09-10,2019-09-10,2019-09-10,603.4480,2019-09-10 11:49:34,DEQJ760331UC0,NC,247
1,E,NC00248,5437,E,2.0,NaN,2019-09-11,2019-09-11,2019-09-11,431.0344,2019-09-11 08:54:14,OIM 060801 GH5,NC,248
2,E,NC00249,1240,C,2.0,NaN,2019-09-11,2019-09-11,2019-09-11,4135.0000,2019-09-11 18:23:06,REMA-710901-G64,NC,249
3,E,NC00250,4889,E,3.0,NaN,2019-09-12,2019-09-12,2019-09-12,258.6200,2019-09-12 14:54:54,MAPA 710520 A10,NC,250
4,E,NC00251,6834,E,2.0,F29452,2019-09-19,2019-09-10,2019-09-19,919.4560,2019-09-19 10:59:28,NPR111214391,NC,251

In [ ]:
#Cambiar valores nulos en la columna VENDEDOR por 0 (cada vendedor tiene un numero)
df_notascredito['VENDEDOR'].fillna(0, inplace=True)

In [ ]:
#SI0000 = Valores en la columna CVE_PEDI que estan en blanco
df_notascredito['CVE_PEDI'].fillna('SI0000', inplace=True)

In [ ]:
#Checar si hay valores nulos por columna
valores_nulos=df_notascredito.isnull().sum()
valores_nulos

TIP_OP        0
CVE_NC        0
CLIENTE       0
STATUS        0
VENDEDOR      0
CVE_PEDI      0
FECHA_DOC     0
FECHA_ENT     0
FECHA_VEN     0
CAN_TOT       0
FECHA_ELAB    0
RFC           0
SERIE         0
FOLIO         0
dtype: int64

## **Clientes**

In [ ]:
#Checar si hay valores nulos por columna
valores_nulos=df_clientes.isnull().sum()
valores_nulos

RFC       15
NOMBRE     1
dtype: int64

In [ ]:
#SI0000 = Valores en la columna CVE_PEDI que estan en blanco
df_clientes['RFC'].fillna('000000000000', inplace=True)

In [ ]:
#la fila MOSTR que tiene valor nulo en mobre es para ventas en mostrador.
df_clientes['NOMBRE'].fillna('MOSTRADOR', inplace=True)

In [ ]:
#Checar si hay valores nulos por columna
valores_nulos=df_clientes.isnull().sum()
valores_nulos

RFC       0
NOMBRE    0
dtype: int64

# **Guardar en un nuevo excel**

In [ ]:
df_facturacion.to_excel("FACTURACION_LIMPIA.xlsx", sheet_name="FACTURACION", index=False)

In [ ]:
#FACTURACION: FILTRO DE FECHA CANCELACIÓN
with pd.ExcelWriter('FACTURACION_LIMPIA.xlsx',mode='a') as writer:
  df_facturacionfiltro.to_excel(writer, sheet_name="FILTRO FACTURACION", index=False)

In [ ]:
with pd.ExcelWriter('FACTURACION_LIMPIA.xlsx',mode='a') as writer:
  df_devoluciones.to_excel(writer, sheet_name="DEVOLUCIONES", index=False)

In [ ]:
#DEVOLUCIONES: FILTRO DE FECHA CANCELACION
with pd.ExcelWriter('FACTURACION_LIMPIA.xlsx',mode='a') as writer:
  df_devolucionesfiltro.to_excel(writer, sheet_name="FILTRO DEVOLUCIONES", index=False)

In [ ]:
with pd.ExcelWriter('FACTURACION_LIMPIA.xlsx',mode='a') as writer:
  df_notascredito.to_excel(writer, sheet_name="NOTAS DE CREDITO", index=False)

In [ ]:
#NOTAS DE CREDITO: FILTRO DE DEVOLUCIONES
with pd.ExcelWriter('FACTURACION_LIMPIA.xlsx',mode='a') as writer:
  filtro_cancelaciones.to_excel(writer, sheet_name="NOTAS DE CREDITO-DEVOLUCIONES", index=False)

In [ ]:
with pd.ExcelWriter('FACTURACION_LIMPIA.xlsx',mode='a') as writer:
  df_clientes.to_excel(writer, sheet_name="CLIENTES", index=True)